### ISSUE TITLE
What version of python should I choose，why not provide a formatted environment.yaml file?

### ISSUE THREAD

**Issue by louquan18** [zangzelin/code_diffaug#2]
I used AI to format the envrionment.yml file, which is used to configure the environment for this project, and I often encounter errors. Why is this happening? I also wrote a script to download packages one by one, but I still encounter various dependency issues.

**Comment by louquan18** [comment]
I recommend that you run the command to check which packages are missing and refer to the configuration file provided by the author to configure your system. In fact, you don't need more than 270 packages, and the dependencies are not complicated. This issue is now resolved.

**Comment by cyang810** [comment]
Could you tell me where to get the data set?☹️

 I want to run 'python./main_diffaug.py fit --config=conf/gast.yaml' , but the error is missing '\namename\data\gast10kwithcelltype.h5ad',

I go to paper provides https://maayanlab.cloud/Harmonizome/gene/GAST, only find 'GAST associations.tsv'

**Comment by louquan18** [comment]
I ran into the same problem, the gast dataset couldn't be found, let's look at other datasets.

Best,
&nbsp;


掘墓人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月28日(星期一) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [zangzelin/code_diffaug] What version of python should I choose，why not provide a formatted environment.yaml file? (Issue #2)














 
Could you tell me where to get the data set?☹️
 
I want to run 'python./main_diffaug.py fit --config=conf/gast.yaml' , but the error is missing '\namename\data\gast10kwithcelltype.h5ad',
 
I go to paper provides https://maayanlab.cloud/Harmonizome/gene/GAST, only find 'GAST associations.tsv'
